#!/bin/sh
clear
echo '======================================='
echo ' PoC by wtm@offensi.com for Google VRP '  
echo ' -  arbitrary evil code goes here ;) - '
echo '======================================='
